// ============================================================
// draw-report-relay
// Recebe a denúncia do Roblox (traços vetoriais + metadados), RENDERIZA o
// desenho em PNG e posta no canal do Discord via webhook (imagem inline).
//
// O Roblox NÃO consegue postar direto em webhooks do Discord — por isso este
// relay existe. Fluxo:  Roblox  ->  (este relay)  ->  Discord webhook
//
// Requer Node 18+ (usa fetch/FormData/Blob globais).
// ============================================================
import express from "express";
import { Resvg } from "@resvg/resvg-js";

const WEBHOOK = process.env.DISCORD_WEBHOOK_URL;
const SECRET  = process.env.RELAY_SECRET;
const PORT    = process.env.PORT || 8080;

if (!WEBHOOK) console.warn("[relay] AVISO: DISCORD_WEBHOOK_URL nao definido.");
if (!SECRET)  console.warn("[relay] AVISO: RELAY_SECRET nao definido.");

const app = express();
app.use(express.json({ limit: "8mb" })); // os tracos podem ter algumas 100s de KB

app.get("/", (_req, res) => res.send("draw-report-relay ok"));

app.post("/report", async (req, res) => {
  try {
      const { secret, report = {}, strokes = [] } = req.body || {};

          // 1) autenticacao por segredo compartilhado (mesmo valor do ModerationServer)
              if (!SECRET || secret !== SECRET) return res.status(401).json({ error: "bad secret" });
                  if (!Array.isArray(strokes) || strokes.length === 0) return res.status(400).json({ error: "no strokes" });

                      // 2) renderiza os tracos -> SVG -> PNG
                          const built = buildSvg(strokes);
                              if (!built) return res.status(400).json({ error: "empty drawing" });
                                  const png = new Resvg(built.svg, { fitTo: { mode: "original" } }).render().asPng();

                                      // 3) monta o embed e sobe a imagem pro Discord (multipart)
                                          const ts = Number(report.timestamp) || Math.floor(Date.now() / 1000);
                                              const embed = {
                                                    title: "🚩 Denuncia de desenho",
                                                          color: 0xed4245,
                                                                fields: [
                                                                        { name: "Autor", value: `${report.authorName ?? "?"} (\`${report.authorUserId ?? "?"}\`)`, inline: true },
                                                                                { name: "Motivo", value: String(report.reason ?? "?"), inline: true },
                                                                                        { name: "Total de denuncias", value: String(report.total ?? 1), inline: true },
                                                                                                { name: "Denunciante", value: `${report.reporterName ?? "?"} (\`${report.reporterUserId ?? "?"}\`)`, inline: true },
                                                                                                        { name: "Place", value: String(report.placeId ?? "?"), inline: true },
                                                                                                                { name: "Servidor (jobId)", value: report.jobId ? `\`${report.jobId}\`` : "—", inline: false },
                                                                                                                      ],
                                                                                                                            image: { url: "attachment://denuncia.png" },
                                                                                                                                  footer: { text: `${built.W}x${built.H}px · ${strokes.length} tracos` },
                                                                                                                                        timestamp: new Date(ts * 1000).toISOString(),
                                                                                                                                            };
                                                                                                                                            
                                                                                                                                                const form = new FormData();
                                                                                                                                                    form.append("payload_json", JSON.stringify({ username: "Moderacao", embeds: [embed] }));
                                                                                                                                                        form.append("files[0]", new Blob([png], { type: "image/png" }), "denuncia.png");
                                                                                                                                                        
                                                                                                                                                            const dr = await fetch(WEBHOOK, { method: "POST", body: form });
                                                                                                                                                                if (!dr.ok) {
                                                                                                                                                                      const t = await dr.text().catch(() => "");
                                                                                                                                                                            console.error("[relay] erro do Discord", dr.status, t.slice(0, 300));
                                                                                                                                                                                  return res.status(502).json({ error: "discord", status: dr.status });
                                                                                                                                                                                      }
                                                                                                                                                                                          res.json({ ok: true });
                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                console.error("[relay] erro interno", e);
                                                                                                                                                                                                    res.status(500).json({ error: "internal" });
                                                                                                                                                                                                      }
                                                                                                                                                                                                      });
                                                                                                                                                                                                      
                                                                                                                                                                                                      // ------------------------------------------------------------
                                                                                                                                                                                                      // Constroi um SVG a partir dos tracos. Auto-enquadra na bounding box (preview
                                                                                                                                                                                                      // focado na arte). Cada traco vira polilinha; "fill" vira poligono; ponto unico
                                                                                                                                                                                                      // vira circulo. Coordenadas vem em "studs" do canvas; escalamos p/ pixels.
                                                                                                                                                                                                      // ------------------------------------------------------------
                                                                                                                                                                                                      function buildSvg(strokes) {
                                                                                                                                                                                                        let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity, maxW = 0;
                                                                                                                                                                                                          for (const s of strokes) {
                                                                                                                                                                                                              const w = Number(s.width) || 0; if (w > maxW) maxW = w;
                                                                                                                                                                                                                  const p = s.pts || [];
                                                                                                                                                                                                                      for (let i = 0; i + 1 < p.length; i += 2) {
                                                                                                                                                                                                                            const x = p[i], y = p[i + 1];
                                                                                                                                                                                                                                  if (x < minX) minX = x; if (x > maxX) maxX = x;
                                                                                                                                                                                                                                        if (y < minY) minY = y; if (y > maxY) maxY = y;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                if (!isFinite(minX)) return null;
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                  const span = Math.max(maxX - minX, maxY - minY);
                                                                                                                                                                                                                                                    const pad = maxW * 0.5 + span * 0.04 + 2;
                                                                                                                                                                                                                                                      minX -= pad; minY -= pad; maxX += pad; maxY += pad;
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                        const wStuds = Math.max(1e-3, maxX - minX);
                                                                                                                                                                                                                                                          const hStuds = Math.max(1e-3, maxY - minY);
                                                                                                                                                                                                                                                            const TARGET = 1024; // maior lado, em px
                                                                                                                                                                                                                                                              const scale = TARGET / Math.max(wStuds, hStuds);
                                                                                                                                                                                                                                                                const W = Math.max(16, Math.round(wStuds * scale));
                                                                                                                                                                                                                                                                  const H = Math.max(16, Math.round(hStuds * scale));
                                                                                                                                                                                                                                                                    const mx = (x) => ((x - minX) * scale).toFixed(2);
                                                                                                                                                                                                                                                                      const my = (y) => ((y - minY) * scale).toFixed(2);
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                        const out = [
                                                                                                                                                                                                                                                                            `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">`,
                                                                                                                                                                                                                                                                                `<rect width="100%" height="100%" fill="#ffffff"/>`,
                                                                                                                                                                                                                                                                                  ];
                                                                                                                                                                                                                                                                                    for (const s of strokes) {
                                                                                                                                                                                                                                                                                        const c = s.color || [0, 0, 0];
                                                                                                                                                                                                                                                                                            const col = `rgb(${c[0] | 0},${c[1] | 0},${c[2] | 0})`;
                                                                                                                                                                                                                                                                                                const op = s.opacity == null ? 1 : Number(s.opacity);
                                                                                                                                                                                                                                                                                                    const sw = Math.max(0.6, (Number(s.width) || 0.5) * scale);
                                                                                                                                                                                                                                                                                                        const p = s.pts || [];
                                                                                                                                                                                                                                                                                                            if (p.length < 2) continue;
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                if (p.length === 2) {
                                                                                                                                                                                                                                                                                                                      out.push(`<circle cx="${mx(p[0])}" cy="${my(p[1])}" r="${(sw / 2).toFixed(2)}" fill="${col}" fill-opacity="${op}"/>`);
                                                                                                                                                                                                                                                                                                                            continue;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    let pts = "";
                                                                                                                                                                                                                                                                                                                                        for (let i = 0; i + 1 < p.length; i += 2) pts += `${mx(p[i])},${my(p[i + 1])} `;
                                                                                                                                                                                                                                                                                                                                            if (s.fill) {
                                                                                                                                                                                                                                                                                                                                                  out.push(`<polygon points="${pts.trim()}" fill="${col}" fill-opacity="${op}"/>`);
                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                            out.push(`<polyline points="${pts.trim()}" fill="none" stroke="${col}" stroke-opacity="${op}" stroke-width="${sw.toFixed(2)}" stroke-linecap="round" stroke-linejoin="round"/>`);
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                    out.push(`</svg>`);
                                                                                                                                                                                                                                                                                                                                                                      return { svg: out.join(""), W, H };
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                      app.listen(PORT, () => console.log(`[relay] ouvindo na porta ${PORT}`));
                                                                                                                                                                                                                                                                                                                                                                      
